name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v4
      with:
        node-version: 23

    - name: Run tests
      run: |
        npm i
        npm run build
        npm run test

    - name: Nightly build
      run: |
        npm run release

    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: dist/
